-- 1장
DESC TEMP;
DESC TDEPT;
SELECT EMP_ID FROM TEMP;
SELECT EMP_NAME, SALARY/18, SALARY*2/18 FROM TEMP;
SELECT EMP_NAME, 100000 + SALARY/18, 200000 + SALARY*2/18 FROM TEMP;
SELECT EMP_NAME FROM TEMP WHERE HOBBY IS NOT NULL;
SELECT EMP_NAME FROM TEMP WHERE HOBBY <> NULL;
SELECT EMP_NAME, NVL(HOBBY,'없음') FROM TEMP;
SELECT EMP_NAME FROM TEMP WHERE NVL(HOBBY,'등산') = '등산';
SELECT EMP_ID SABUN, EMP_NAME AS NAME FROM TEMP;
SELECT EMP_ID, DEPT_CODE, DEPT_NAME FROM TEMP, TDEPT WHERE TDEPT.DEPT_CODE = TEMP.DEPT_CODE;
SELECT EMP_ID, TEMP.DEPT_CODE, DEPT_NAME FROM TEMP, TDEPT WHERE TDEPT.DEPT_CODE = TEMP.DEPT_CODE;
SELECT A.EMP_ID, A.DEPT_CODE, B.DEPT_NAME FROM TEMP A, TDEPT B WHERE A.DEPT_CODE = B.DEPT_CODE;
SELECT A.EMP_ID, A.EMP_NAME, B.BOSS_ID, C.EMP_NAME FROM TEMP A, TDEPT B, TEMP C WHERE B.DEPT_CODE = A.DEPT_CODE AND C.EMP_ID = B.BOSS_ID;
SELECT EMP_ID AS 사번, EMP_NAME AS 성명 FROM TEMP;
SELECT EMP_NAME || '(' || LEV || ')' 성명 FROM TEMP;
SELECT EMP_NAME || ''''|| LEV || '''' 성명 FROM TEMP;
SELECT OBJECT_NAME, OBJECT_TYPE FROM USER_OBJECTS;
SELECT 'DROP ' || OBJECT_TYPE || ' ' || OBJECT_NAME || ';' FROM USER_OBJECTS;
SELECT EMP_ID || '  '|| EMP_NAME || '   ' || LEV FROM TEMP;
SELECT EMP_ID || EMP_NAME FROM TEMP;
SELECT EMP_ID, EMP_NAME FROM TEMP WHERE SUBSTR(EMP_ID,1,4) + 1 = 1998;
SELECT '''' || EMP_NAME || BIRTH_DATE || '''' NAME_BIRTH FROM TEMP;
SELECT EMP_NAME FROM TEMP WHERE HOBBY = '등산';
SELECT EMP_ID, EMP_NAME FROM TEMP;
SELECT EMP_ID, EMP_NAME FROM TEMP WHERE EMP_ID > 0;
EXPLAIN PLAN SET STATEMENT_ID= '임의지정' FOR
SELECT EMP_ID, EMP_NAME FROM TEMP WHERE EMP_ID > 0;
SELECT INDEX_NAME FROM USER_INDEXES WHERE TABLE_NAME = 'TEMP';
SELECT INDEX_NAME, COLUMN_NAME FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'TEMP';
SELECT EMP_ID, EMP_NAME, HOBBY FROM TEMP WHERE LEV = '과장' AND HOBBY IS NOT NULL;
SELECT EMP_ID,EMP_NAME FROM TEMP ORDER BY EMP_ID;
SELECT EMP_ID,EMP_NAME FROM TEMP ORDER BY EMP_ID DESC;
SELECT LEV,EMP_ID,EMP_NAME FROM TEMP ORDER BY 1,2 DESC;
SELECT * FROM TDEPT ORDER BY AREA;
SELECT EMP_ID,EMP_NAME,DEPT_CODE FROM TEMP WHERE DEPT_CODE LIKE 'A%';
SELECT EMP_ID,EMP_NAME,DEPT_CODE FROM TEMP WHERE DEPT_CODE LIKE '%A%';
SELECT EMP_ID,EMP_NAME,DEPT_CODE FROM TEMP WHERE DEPT_CODE LIKE '_A____';
SELECT EMP_ID,EMP_NAME FROM TEMP WHERE EMP_ID BETWEEN 19970001 AND 19979999;
SELECT EMP_ID, EMP_NAME FROM TEMP WHERE EMP_NAME BETWEEN '가' AND '나';
SELECT EMP_ID,EMP_NAME FROM TEMP WHERE EMP_NAME IN ('홍길동','김길동');
SELECT EMP_ID,EMP_NAME FROM TEMP WHERE EMP_NAME = '김길동' OR EMP_NAME = '홍길동';
SELECT LEV, MAX(SALARY) MAX_SAL FROM TEMP GROUP BY LEV;
SELECT MAX(SALARY) FROM TEMP;
SELECT LEV FROM TEMP GROUP BY LEV;
SELECT MIN(BOSS_ID || DEPT_CODE) FROM TDEPT;
SELECT LEV, MAX(SALARY) MAX_SAL FROM TEMP GROUP BY LEV;
SELECT AREA, MIN(BOSS_ID) FROM TDEPT GROUP BY AREA ORDER BY 2;
SELECT LEV,AVG(SALARY) FROM TEMP GROUP BY LEV HAVING AVG(SALARY) > 50000000;
SELECT LEV,MAX(EMP_ID) FROM TEMP GROUP BY LEV HAVING MAX(EMP_ID) LIKE '1997%';


-- 2장
SELECT INSTR('ABC좋은나라DEF웃긴나라','D'), INSTR('ABC좋은나라DEF웃긴나라','나') FROM DUAL;
SELECT INSTRB('ABC좋은나라DEF웃긴나라','D'), INSTRB('ABC좋은나라DEF웃긴나라','나') FROM DUAL;
SELECT INSTR('ABC좋은나라DEF웃긴나라','나',1,2) FROM DUAL;
SELECT INSTR('ABC좋은나라DEF웃긴나라','나',7,1) FROM DUAL;
SELECT INSTR('ABC좋은나라DEF웃긴나라','다') FROM DUAL;
SELECT INSTR('ABC좋은나라DEF웃긴나라','웃긴') FROM DUAL;
SELECT SUBSTR('ABC좋은나라DEF웃긴나라',2,10) FROM DUAL;
SELECT SUBSTRB('ABC좋은나라DEF웃긴나라',2,10) FROM DUAL;
SELECT SUBSTRB('ABC좋은나라DEF웃긴나라',2,10) FROM DUAL;
SELECT SUBSTR('ABC좋은나라DEF웃긴나라',-4,2) FROM DUAL;
SELECT SUBSTR('ABC좋은나라DEF웃긴나라',4,4), SUBSTRB('ABC좋은나라DEF웃긴나라',4,8) FROM DUAL;
SELECT LENGTH('ABC좋은나라DEF웃긴나라') FROM DUAL;
SELECT LENGTHB('ABC좋은나라DEF웃긴나라') FROM DUAL;
SELECT LENGTHB('ABC좋은나라DEF웃긴나라') - LENGTH('ABC좋은나라DEF웃긴나라') FROM DUAL;
SELECT LPAD(DEPT_NAME,10,'*') FROM TDEPT;
SELECT LPAD(DEPT_NAME,10,'123456789') FROM TDEPT;
SELECT RPAD(DEPT_NAME,10,'*') FROM TDEPT;
SELECT RPAD(DEPT_NAME,10, SUBSTR('1234567890',LENGTHB(DEPT_NAME)+1)) FROM TDEPT;
SELECT REPLACE('ABC좋은나라DEF웃긴나라','나라','**') FROM DUAL;
SELECT REPLACE(REPLACE('ABC좋은나라DEF웃긴나라','ABC',''),'DEF','') FROM DUAL;
SELECT CHR(65) FROM DUAL;
SELECT ASCII('A') FROM DUAL;
SELECT EMP_ID||CHR(10)||EMP_NAME EMP FROM TEMP;
SELECT ROUND('1234.567',1), ROUND('1234.567',-1), ROUND('1234.567') FROM DUAL;
SELECT TRUNC('1234.567',1), TRUNC('1234.567',-1), TRUNC('1234.567') FROM DUAL;
SELECT SIGN(-10), SIGN(0), SIGN(10),SIGN(NULL) FROM DUAL;
SELECT CEIL(2),CEIL(2.1) FROM DUAL;
SELECT FLOOR (2), FLOOR (2.1) FROM DUAL;
SELECT MOD (1,3), MOD (2,3), MOD (3,3), MOD (4,3) FROM DUAL;
-- CREATE TABLE MOD_TEST AS SELECT ROWNUM NO FROM TEMP;
SELECT NO, MOD(NO-1,3)+ 1 OUT FROM MOD_TEST;
SELECT POWER(2,NO) FROM MOD_TEST;
-- SELECT SYSDATE + BIRTH_DATE FROM TEMP WHERE EMP_NAME = '홍길동'; 
-- SELECT SYSDATE ? BIRTH_DATE FROM TEMP WHERE EMP_NAME = '홍길동'; 
SELECT BIRTH_DATE,BIRTH_DATE + 1, BIRTH_DATE - 1 FROM TEMP WHERE EMP_NAME = '홍길동';
SELECT TO_CHAR(BIRTH_DATE,'HH24:MI:SS') BIRTH_TIME, TO_CHAR(BIRTH_DATE + 14/24,'HH24:MI:SS') AS TIME
, TO_CHAR(BIRTH_DATE + 30/(24*60) ,'HH24:MI:SS') AS MIN, TO_CHAR(BIRTH_DATE+ 50/(24*60*60) ,'HH24:MI:SS') AS SEC FROM TEMP WHERE EMP_NAME = '홍길동';
SELECT BIRTH_DATE, ADD_MONTHS(BIRTH_DATE,1) , -- 한달 더하기
ADD_MONTHS(BIRTH_DATE,-13) -- 13개월 빼기
FROM TEMP WHERE EMP_NAME = '홍길동';
SELECT MONTHS_BETWEEN(SYSDATE,BIRTH_DATE) MON_TERM FROM TEMP WHERE EMP_NAME = '홍길동';
SELECT MONTHS_BETWEEN(BIRTH_DATE,SYSDATE) , BIRTH_DATE, ADD_MONTHS(SYSDATE,MONTHS_BETWEEN(BIRTH_DATE,SYSDATE)),
ADD_MONTHS(SYSDATE,TRUNC(MONTHS_BETWEEN(BIRTH_DATE,SYSDATE))), ADD_MONTHS(SYSDATE,ROUND(MONTHS_BETWEEN(BIRTH_DATE,SYSDATE))) FROM TEMP;
SELECT BIRTH_DATE,LAST_DAY(BIRTH_DATE) FROM TEMP;
SELECT TO_CHAR(SYSDATE,'YY/MM/DD') DATE1, TO_CHAR (SYSDATE,'YYYY.MM.DD') DATE2, TO_CHAR (SYSDATE,'Month DD.YYYY') DATE3
, TO_CHAR (SYSDATE,'DY DD MON YY') DATE4, TO_CHAR (SYSDATE,'Day Mon DD') DATE5 FROM DUAL;
SELECT EMP_ID, TO_CHAR(BIRTH_DATE,'YYYY "년" MM "월" DD "일" DAY') BIRTH FROM TEMP;
-- SELECT TO_CHAR(1234,'09,999') NUMBER1, TO_CHAR(1234.56,'99,999.99') NUMBER2, TO_CHAR(1234,'$99,999') NUMBER3,
-- TO_CHAR(1234,'L99,999') NUMBER4, TO_CHAR(-1234,'99,999MI') NUMBER5,  TO_CHAR(-1234,'99,999EEEE') NUMBER6 FROM DUAL;
-- SELECT TO_CHAR(SALARY,'099,999,999') NUMBER1, TO_CHAR(SALARY,'999,999,999.99') NUMBER2, TO_CHAR(SALARY,'$999,999,999') NUMBER3,
-- TO_CHAR(SALARY,'L999,999,999') NUMBER4, TO_CHAR(SALARY,'999,999,999MI') NUMBER5, TO_CHAR(SALARY,'999,999,999EEEE') NUMBER6 FROM TEMP;
SELECT TO_NUMBER('123456') TONUM1, TO_NUMBER('123,456','999,999') TONUM2 FROM DUAL;
SELECT TO_DATE('1997-12-31 13:33:44','YYYY-MM-DD HH24:MI:SS') FROM DUAL;
-- SELECT SYSDATE ? TO_DATE('19700101','YYYYMMDD') FROM DUAL;
SELECT TO_DATE('19700101000000','YYYYMMDDHH24MISS') + 946075441 / (24*60*60) FROM DUAL;
SELECT COUNT(*),COUNT(8) FROM TEMP;
SELECT COUNT(EMP_ID) CNT1, COUNT(HOBBY) CNT2 FROM TEMP;
SELECT LEV, COUNT(*), COUNT(HOBBY) FROM TEMP GROUP BY LEV;
SELECT COUNT(*) FROM TEMP WHERE HOBBY = '공부';
SELECT COUNT(*) FROM TEMP WHERE LEV = '과장' AND SALARY >= 40000000;
SELECT COUNT(DISTINCT LEV) FROM TEMP;
SELECT MIN(EMP_ID) FROM TEMP;
SELECT LEV, MIN(EMP_ID) FROM TEMP GROUP BY LEV;
SELECT LEV, SUBSTR(MIN(LPAD(TO_CHAR(SALARY),10,'0')||EMP_ID),11) EMP_ID,MIN(SALARY) SAL FROM TEMP GROUP BY LEV;
SELECT LEV, SUM(SALARY) SUM_SAL, AVG(SALARY) AVG1, SUM(SALARY)/COUNT(*) AVG2 FROM TEMP GROUP BY LEV;
-- UPDATE TEMP SET SALARY = 0 WHERE EMP_NAME = '홍길동';
SELECT AVG(SALARY) FROM TEMP;
-- UPDATE TEMP SET SALARY = NULL WHERE EMP_NAME = '홍길동';


-- 3장
DESC EMP_LEVEL;
SELECT EMP_ID FROM TEMP UNION
SELECT EMP_ID FROM TCOM;
--SELECT EMP_ID,EMP_NAME FROM TEMP UNION
--SELECT EMP_ID,BONUS_RATE FROM TCOM;
--SELECT EMP_ID FROM TEMP UNION
--SELECT EMP_ID,BONUS_RATE FROM TCOM;
SELECT EMP_ID,SALARY,0 COMM FROM TEMP UNION
SELECT EMP_ID,0 SALARY,COMM FROM TCOM;
SELECT EMP_ID FROM TEMP UNION ALL
SELECT EMP_ID FROM TCOM;
SELECT EMP_ID FROM TEMP UNION ALL 
SELECT EMP_ID FROM TCOM ORDER BY 1;
SELECT EMP_ID,SALARY,0 COMM FROM TEMP UNION ALL 
SELECT EMP_ID,0 SALARY,COMM FROM TCOM;
SELECT EMP_ID FROM TEMP INTERSECT
SELECT EMP_ID FROM TCOM;
SELECT EMP_ID FROM TEMP MINUS 
SELECT EMP_ID FROM TCOM;
(SELECT EMP_ID FROM TEMP INTERSECT SELECT EMP_ID FROM TCOM) UNION
(SELECT EMP_ID FROM TEMP MINUS SELECT EMP_ID FROM TCOM);
SELECT COUNT(*) FROM TEMP,TCOM;
SELECT NO,A.EMP_ID,A.EMP_NAME,A.SALARY FROM TEMP A, MOD_TEST B WHERE B.NO <= 2 AND A.LEV = '과장';
SELECT A.EMP_ID, A.EMP_NAME, A.DEPT_CODE,B.DEPT_NAME FROM TEMP A,TDEPT B WHERE B.DEPT_CODE = A.DEPT_CODE;
SELECT A.EMP_ID,A.EMP_NAME, A.SALARY+B.COMM FROM TEMP A,TCOM B WHERE A.EMP_ID > 0 AND B.EMP_ID = A.EMP_ID AND B.WORK_YEAR = '2001';
SELECT B.LEV 직급, A.EMP_ID 사번, A.EMP_NAME 성명, A.BIRTH_DATE 나이, A.LEV 현재직급 FROM TEMP A, EMP_LEVEL B
WHERE A.BIRTH_DATE BETWEEN ADD_MONTHS(SYSDATE,-1*TO_AGE*12) AND ADD_MONTHS(SYSDATE,-1*FROM_AGE*12) AND B.LEV = '과장';
SELECT A.EMP_ID,B.EMP_ID FROM TEMP A,TCOM B WHERE B.WORK_YEAR = '2001' AND B.EMP_ID = A.EMP_ID;
SELECT A.EMP_ID,B.EMP_ID FROM TEMP A,TCOM B WHERE B.WORK_YEAR(+) = '2001' AND B.EMP_ID(+) = A.EMP_ID;
SELECT B.EMP_ID 사번, B.EMP_NAME 성명, B.SALARY 연봉, A.FROM_SAL 하한, A.TO_SAL 상한 FROM EMP_LEVEL A,TEMP B WHERE B.LEV = A.LEV(+);
SELECT A.DEPT_CODE 부서코드, A.DEPT_NAME 부서명, B.DEPT_CODE 상위부서코드, B.DEPT_NAME 상위부서명 FROM TDEPT A,TDEPT B WHERE B.DEPT_CODE = A.PARENT_DEPT;
SELECT A.EMP_ID "사번", A.EMP_NAME "성명", A.BIRTH_DATE "생일", COUNT(B.BIRTH_DATE) "자신보다 생일이 빠른 사람의 수" FROM TEMP A,TEMP B WHERE B.BIRTH_DATE(+) < A.BIRTH_DATE
GROUP BY A.EMP_ID,A.EMP_NAME,A.BIRTH_DATE ORDER BY COUNT(B.BIRTH_DATE);
SELECT A.EMP_ID, A.EMP_NAME, B.DEPT_CODE, B.DEPT_NAME, C.DEPT_CODE, C.DEPT_NAME, D.EMP_ID, D.EMP_NAME FROM TEMP A,TDEPT B,TDEPT C,TEMP D
WHERE B.DEPT_CODE = A.DEPT_CODE AND C.DEPT_CODE = B.PARENT_DEPT AND C.DEPT_CODE = 'CA0001' AND D.EMP_ID = C.BOSS_ID;
SELECT EMP_ID,EMP_NAME FROM TEMP WHERE SALARY = (SELECT MAX(SALARY) FROM TEMP);
SELECT EMP_ID,EMP_NAME,SALARY FROM TEMP WHERE SALARY > (SELECT AVG(SALARY) FROM TEMP);
SELECT EMP_ID,EMP_NAME FROM TEMP WHERE DEPT_CODE IN (SELECT DEPT_CODE FROM TDEPT WHERE AREA = '인천');
SELECT B.DEPT_NAME,COUNT(*) FROM TEMP A,TDEPT B WHERE B.DEPT_CODE = A.DEPT_CODE AND A.EMP_ID IN (SELECT EMP_ID FROM TCOM) GROUP BY B.DEPT_NAME;
SELECT EMP_ID,EMP_NAME FROM TEMP WHERE (DEPT_CODE,EMP_ID) IN (SELECT DEPT_CODE,BOSS_ID FROM TDEPT );
SELECT EMP_ID, EMP_NAME,SALARY FROM TEMP WHERE (DEPT_CODE,SALARY) IN (SELECT DEPT_CODE,MAX(SALARY) FROM TEMP GROUP BY DEPT_CODE);
SELECT EMP_ID,EMP_NAME FROM TEMP A WHERE SALARY > (SELECT AVG(SALARY) FROM TEMP B WHERE B.LEV = A.LEV);
--UPDATE TDEPT A SET A.BOSS_ID = (SELECT MIN(B.EMP_ID) FROM TEMP B WHERE B.DEPT_CODE = A.DEPT_CODE);
--INSERT INTO TCOM (WORK_YEAR,EMP_ID,BONUS_RATE,COMM) SELECT '2002',EMP_ID,0.1,SALARY*0.1 FROM TEMP;
SELECT EMP_ID,EMP_NAME,SALARY FROM TEMP WHERE SALARY > ANY (SELECT SALARY FROM TEMP WHERE LEV = '과장');
SELECT EMP_ID,EMP_NAME,SALARY FROM TEMP WHERE SALARY > ALL (SELECT SALARY FROM TEMP WHERE LEV = '과장');
SELECT EMP_ID,EMP_NAME,SALARY FROM TEMP A WHERE EXISTS (SELECT B.SALARY FROM TEMP B WHERE B.LEV = '과장' AND A.SALARY > B.SALARY);


-- 4장 (61p)


-- 5장


-- 6장


-- 7장


-- 8장


-- 9장


-- 10장

-- 11장
-- 12장
-- 13장
-- 14장
-- 15장
-- 16장
-- 17장
-- 18장
-- 19장
-- 20장
-- 21장
-- 22장
-- 23장
-- 24장
-- 25장
-- 26장
-- 27장
-- 28장
-- 29장
-- 30장
-- 31장
-- 32장
-- 33장
